name: Create Release Draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v prefix)'
        required: true
        type: string
      description:
        description: 'Release description'
        required: false
        type: string
        default: ''

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Native Youtube v${{ github.event.inputs.version }}
        body: |
          # Native Youtube v${{ github.event.inputs.version }}
          
          ## What's New
          
          ${{ github.event.inputs.description }}
          
          ## Installation
          
          ### New Users
          Download the DMG file and drag Native Youtube to your Applications folder.
          
          ### Existing Users
          Native Youtube will automatically check for updates and notify you when this release is available.
          
          ## Download
          
          - **DMG**: For manual installation  
          - **ZIP**: For Sparkle auto-update
          
          ---
          
          _This is a draft release. The assets will be automatically uploaded when the release is published._
        draft: true
        prerelease: false
        
    - name: Output Release URL
      run: |
        echo "Release created at: ${{ steps.create_release.outputs.html_url }}"
        echo "Next steps:"
        echo "1. Edit the release notes as needed"
        echo "2. Publish the release to trigger the build workflow"
        echo "3. Assets will be automatically uploaded and appcast.xml will be updated"